version: "3.8"

services:
  nextjs:
    image: sondngyn/github-feedback:latest
    ports:
      - "3000:3000"
    container_name: gh-next
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    volumes:
      - /app/node_modules
      - /app/.next
    restart: always
    environment:
      - NODE_ENV=production
      - PRIVATE_KEY=${PRIVATE_KEY}
      - APP_ID=${APP_ID}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}

  frontend:
    image: nginx:latest
    container_name: gh-nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - nextjs
    restart: always