version: "3.8"

services:
  nextjs:
    container_name: gh-next
    image: gh-next
    ports:
      - "3000:3000"
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - nextjs-dev-node_modules:/app/node_modules
      - nextjs-dev-next:/app/.next
    restart: always
  frontend:
    container_name: gh-nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    entrypoint: ""
    ports:
      - "80:80"
    depends_on:
      - nextjs
    restart: always

volumes:
  nextjs-dev-node_modules:
  nextjs-dev-next: